### PR TITLE
Cmssw 7 3 x to merge

### PR DESCRIPTION
**Pull request by EmyrClement**
# PHYS14

First changes to run 13 TeV analysis on PHYS14 samples

## Control plots
I began updating make_control_plots.py, but I hope this will now be superseded by the version that reads the ntuple output from AT.

One of the main changes so far.  make_control_plots_fromTrees.py can read in the trees produced by AT and produce plots.  Similarly:

## Fitting
I've begun updating 01_get_fit_results to read in the ntuple output from AT and fit the histograms.  Not perfect yet, and only considers the "central" analysis mode.

## Binning
produceUnfoldingHistograms.py has been updated.  Main changes are to produce fine binned histograms for visible phase space as well as full phase space.  00_pick_bins and make_binning_plots also work.

### CODE REVIEW

**Comment by EmyrClement** [comment]
Just realised something went wrong whilst tidying up...

**Comment by EmyrClement** [comment]
Some work was lost due to me messing up with git.

Also re-added functionality to get qcd template from data.

**Comment by kreczko** [comment]
Please fix
```
File "/home/travis/build/BristolTopGroup/DailyPythonScripts/test/config_XSectionConfig.py", line 13, in setUp
self.config_7TeV = XSectionConfig( centre_of_mass_energy = 7 )
File "/home/travis/build/BristolTopGroup/DailyPythonScripts/config/__init__.py", line 58, in __init__
raise AttributeError( 'Unknown centre of mass energy' )
AttributeError: Unknown centre of mass energy
```
We will need to keep 7 & 8 TeV setup.

**Comment by EmyrClement** [comment]
Seems to have been fixed!

**Comment by kreczko** [comment]
awesome. I guess one good thing about keeping the older centre-of-mass energies is that the code is written to be more dynamic (aka with changes in mind).
BTW: you can also run the tests locally/soolin if you have DPS set up. Either with nosetest or just python (most of the tests are python unit tests)

**Pull request merged**
